CREATE TABLE Department
(
  Code VARCHAR(10) NOT NULL,
  Name VARCHAR(10) NOT NULL,
  Chairman VARCHAR(10) NOT NULL,
  PRIMARY KEY (Code)
);

CREATE TABLE Professor
(
  NetID VARCHAR(10) NOT NULL,
  Department VARCHAR(10) NOT NULL,
  Rank VARCHAR(10) NOT NULL,
  Last_Name VARCHAR(10) NOT NULL,
  First_Name VARCHAR(10) NOT NULL,
  Code VARCHAR(10) NOT NULL,
  PRIMARY KEY (NetID),
  FOREIGN KEY (Code) REFERENCES Department(Code)
);

CREATE TABLE Student
(
  NetID VARCHAR(10) NOT NULL,
  Last_Name VARCHAR(10) NOT NULL,
  FIrst_Name VARCHAR(10) NOT NULL,
  Status_Undergraduate_Graduate VARCHAR(10) NOT NULL,
  Major VARCHAR(10)NOT NULL,
  PRIMARY KEY (NetID),
  FOREIGN KEY (NetID) REFERENCES Professor(NetID)
);

CREATE TABLE Courses
(
  CourseID VARCHAR(10)NOT NULL,
  Course_Name VARCHAR(10)NOT NULL,
  Department VARCHAR(10) NOT NULL,
  Semester VARCHAR(10) NOT NULL,
  Year VARCHAR(10) NOT NULL,
  NetID VARCHAR(10) NOT NULL,
  NetID VARCHAR(10) NOT NULL,
  PRIMARY KEY (CourseID),
  FOREIGN KEY (NetID) REFERENCES Student(NetID),
  FOREIGN KEY (NetID) REFERENCES Professor(NetID)
);
